# Monitor
monitor=,preferred,auto,1

# Programs
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun

# Autostart
exec-once = waybar
exec-once = nm-applet
exec-once = blueman-applet
exec-once = polkit-gnome-authentication-agent-1

# Environment
env = XCURSOR_SIZE,24

# Input
input {
    kb_layout = us
    follow_mouse = 1
}

# General
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    layout = dwindle
}

# Decoration
decoration {
    rounding = 8
}

# Animations
animations {
    enabled = yes
}

# Keybinds
$mainMod = SUPER

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, D, exec, $menu
bind = $mainMod, Q, killactive
bind = $mainMod, E, exec, dolphin
bind = $mainMod, F, fullscreen
bind = $mainMod, V, togglefloating

# Enter resize submap
bind = $mainMod, R, submap, resize

submap = resize
    binde = , right, resizeactive, 30 0
    binde = , left,  resizeactive, -30 0
    binde = , up,    resizeactive, 0 -30
    binde = , down,  resizeactive, 0 30

    binde = , l, resizeactive, 30 0
    binde = , h, resizeactive, -30 0
    binde = , k, resizeactive, 0 -30
    binde = , j, resizeactive, 0 30

    # Exit submap
    bind = , escape, submap, reset
    bind = $mainMod, R,     submap, reset
submap = reset

# Apps shortcuts
bind = $mainMod, B, exec, firefox
bind = $mainMod, O, exec, obs
bind = $mainMod, N, exec, blender

# Workspace switching
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Move window
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2

# Screenshot
bind = , PRINT, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +%s).png

# Power menu
bind = $mainMod SHIFT, E, exec, wlogout
bind = , XF86MonBrightnessUp, exec, brightnessctl set +10%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 10%-
bind = ,XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = ,XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = ,XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

exec-once = swww-daemon
exec-once = sleep 1 && swww img /home/obsidian/Pictures/wallpapernew.png

# Minimize/unminimize (toggle)
bind = SUPER, M, togglespecialworkspace, minimized
bind = SUPER SHIFT, M, movetoworkspacesilent, special:minimized

#move window
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d


#Vim Keybinds
bind = SUPER, h, movefocus, l 
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d



